server:
  port: 8004
spring:
  boot:
    admin:
      discovery:
        ignored-services:
          - "consul"
          - "rabbitmq"
management:
  endpoints:
    web:
      exposure:
        include: "*"
endpoints:
  prometheus:
    enabled: true